### ISSUE TITLE
mysql setting a uniqe constraint on std::string type

### ISSUE THREAD

**Issue by oldmammuth** [loentar/ngrest-db#3]
I got this error:

> #1071 - Specified key was too long; max key length is 767 bytes

from the mysql backend, while trying to set a

``` cpp 
//*unique: true
std::string mystring;
```
on a c++ ```std::string``` type.

A quick search got me these results:

- using InnoDb as backend, if you use utf8 then the limit is ```varchar(255)```; on *ngrest-db* the default string is ```varchar(256)```. Source of info: http://bugs.mysql.com/bug.php?id=6604 which is not a bug, but a **declared limitation**
- As of http://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes there are various solutions

Since I needed it in a project I considered few possibilities:

1. Set ```innodb_large_prefix```, which was introduced in MySQL 5.5.14 and allows you to include columns up to 3072 bytes long in InnoDB indexes. 
Command to the whole db: 
``` sql 
set global innodb_large_prefix = ON;
```
LIMITATION: This might be useful, but it affects all dbs, and I don't know how much overhead it will cost in terms of storage dimensions.

2. Set a larger prefix to a subset of the column, like so: 
``` sql 
ALTER TABLE `mytable` ADD UNIQUE KEY `mystring` ( `mystring`(255) );
```
It is also possible to do it inside the **table creation query**, with this code inserted after the fields declaration:
``` sql
CONSTRAINT mystring UNIQUE (mystring(255))
```
LIMITATION: This affects only the first 255 bystes, i.e., if there are sequential keys 256 bytes long, and of these the last one only the last one changes, they can't be indexed, because 255 bytes are still the same... this however is a very specific case, not one actually happening any day soon (imho).

3. Recompile *MySqlDb.cpp* and change the string limit from 256 to 255 bytes, like so:
(from line 582)
``` cpp
    static const std::string types[size] = {
        "VOID",
        "TINYINT",
        "INTEGER",
        "BIGINT",
        "DOUBLE",
        "INTEGER",
        "VARCHAR(255)" //changed from "VARCHAR(256)" for InnoDb unique key issues
    };
```
LIMITATION: This change effectively breacks the compatibility with the postgres backend (which is still 256); however, there is still no compat with sqlite where a text doesn't have a fixed lenght, so it should not be a problem to have default strings larger/shorter in different DB backends. Additionally, it may breack the code somewhere else, because it is setting a more restrictive contraint than there was before (strings shorter by a byte)

Personally, I chose to recompile the code with a VARCHAR(255) because it was the quickest fix to the problem, and since it is my project I don't mind the limitation, as long as i know it's in place.

However I found solution 2 a better option, if it were possible to apply consistently inside the code, upoon table creation (with either of the two methods); the only thing is that it means a larger change to the code, and since I didn't have a chance to study the code better, to see where and how implement the changes, I was afraid of messing up and have code breaking somewhere else. (note aside, it could be useful in this case the snippet of code you put at the end of the *README.md*, where after creating all tables, you apply changes to them to insert data and set the autoinsertion... it is sufficient to pass a query with the ```unique key``` creation there, instead of setting the ```// *unique: true``` inside the *struct*. However, I have an issue, by which the code doesn't get executed, and I don't know if it's my code or a real bug, so for now I didn't try that method)

Anyway, thank you for this project, it's great and really it's solving some serious problems I have (the only other real solution is to use python, or worse java... I like the idea of having some code that I can test in a small server, and then compile as module of apach, so three thumbs up for the great job you did!)

**Comment by loentar** [comment]
ngrest-db converts standard C++ types to best match to SQL types. By default std::string is mapped to `varchar(256)` for mysql.

You can change mapped SQL type by defining "type" metacomment:

https://github.com/loentar/ngrest-db/blob/master/examples/example1/src/datatypes.h#L21

So, adding this line before that field should solve the problem:

```
// *type: VARCHAR(255)
```

**Comment by oldmammuth** [comment]
Thank you!
This is a much better solution than to recompile the code. However I thought of writing that big stuff because it's a bit awkward that standard strings can't be make unique out-of-the-box without defining the type limitation... I was just proposing a way to have it all work out-of-the-box.
Anyway, this solution actually fits better my way of coding, because I hadn't notice on can set the type conversion... This is actually very useful,because I have some geospatial data in another project that I can pass to a postgres db with postgis extensions.
Thank you very much for your explanation and prompt anwer!

**Comment by loentar** [comment]
Agree regarding unique constraint must work out of the box. Fix committed.
