### ISSUE TITLE
How can I start ngrest-db under Windows?

### ISSUE THREAD

**Issue by MonKeyXie** [loentar/ngrest-db#4]
I had installed MSYS2 and executed by "Installation guide with screenshots Windows"(https://github.com/loentar/ngrest/wiki/Installation-guide-with-screenshots-Windows),

but I'm using Windows and I don't know how to Add it to my project,all examples are running in the LINUX environment as the command line .Or may I should run it in the linux environment?

Finally,hope to receive your reply.

Thanks!

**Comment by loentar** [comment]
Under Windows the commands are the same as in Linux.

If you're using Windows 10, you can try to install Ubuntu subsystem from add/remove software and work from bash command prompt. This is a easiest way to start ngrest I think.

If you have other questions, feel free to ask at https://groups.google.com/forum/#!forum/ngrest

**Comment by MonKeyXie** [comment]
Thank you very much~I use  CentOS 64 to do it.
